const BLOG_POSTS = [
  {
    id: 1,
    title: "The Art of Minimalistic Design in Modern Web Development",
    excerpt: "Exploring how less can be more when it comes to creating engaging user experiences that truly matter.",
    categories: ["Design", "UX", "Inspiration"],
    readTime: "5 min read",
    date: "Dec 15, 2024",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1000&h=600&fit=crop",
  },
  {
    id: 2,
    title: "Building Scalable React Applications with TypeScript",
    excerpt: "A deep dive into architectural patterns and best practices for maintainable React codebases.",
    categories: ["Development", "TypeScript", "Best Practices"],
    readTime: "8 min read",
    date: "Dec 10, 2024",
    image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=1000&h=600&fit=crop",
  },
  {
    id: 3,
    title: "The Psychology of Color in Digital Interfaces",
    excerpt: "Understanding how color choices influence user behavior and emotional responses in digital products.",
    categories: ["UX", "Design", "Psychology"],
    readTime: "6 min read",
    date: "Dec 5, 2024",
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=1000&h=600&fit=crop",
  },
  {
    id: 4,
    title: "Advanced CSS Grid Techniques for Complex Layouts",
    excerpt: "Mastering CSS Grid to create sophisticated, responsive layouts that adapt to any screen size.",
    categories: ["CSS", "Development", "Layout"],
    readTime: "7 min read",
    date: "Nov 28, 2024",
    image: "https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?w=1000&h=600&fit=crop",
  },
  {
    id: 5,
    title: "The Future of Web Development: Trends to Watch",
    excerpt: "Exploring emerging technologies and methodologies that will shape the next generation of web experiences.",
    categories: ["Trends", "Development", "Innovation"],
    readTime: "6 min read",
    date: "Nov 20, 2024",
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1000&h=600&fit=crop",
  },
  {
    id: 6,
    title: "Optimizing Performance in Modern React Apps",
    excerpt: "Practical strategies and techniques to enhance the speed and efficiency of your React applications.",
    categories: ["Performance", "Development", "React"],
    readTime: "9 min read",
    date: "Nov 15, 2024",
    image: "https://images.unsplash.com/photo-1551650975-87deedd944c3?w=1000&h=600&fit=crop",
  },
  {
    id: 7,
    title: "Exploring Progressive Web Apps",
    excerpt: "Learn how PWAs are bridging the gap between mobile and web applications with offline capabilities.",
    categories: ["Development", "PWA", "Mobile"],
    readTime: "7 min read",
    date: "Nov 10, 2024",
    image: "https://images.unsplash.com/photo-1506765515384-028b60a970df?w=1000&h=600&fit=crop",
  },
  {
    id: 8,
    title: "Accessibility in Web Design",
    excerpt: "Discover the principles and practices for building inclusive digital experiences.",
    categories: ["Design", "Accessibility", "UX"],
    readTime: "8 min read",
    date: "Nov 5, 2024",
    image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=1000&h=600&fit=crop",
  },
  {
    id: 9,
    title: "Serverless Architecture Explained",
    excerpt: "Understanding the benefits and trade-offs of serverless computing in modern cloud environments.",
    categories: ["Development", "Cloud", "Serverless"],
    readTime: "10 min read",
    date: "Oct 30, 2024",
    image: "https://images.unsplash.com/photo-1543269865-cbf427effbad?w=1000&h=600&fit=crop",
  },
  {
    id: 10,
    title: "Mastering the Art of Debugging",
    excerpt: "Tips and tricks to effectively identify and resolve bugs in your codebase.",
    categories: ["Development", "Debugging", "Tooling"],
    readTime: "5 min read",
    date: "Oct 25, 2024",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1000&h=600&fit=crop",
  },
  {
    id: 11,
    title: "The Role of Micro-Interactions in UX",
    excerpt: "How small design elements can create huge impacts on the user experience.",
    categories: ["UX", "Interaction Design", "Motion"],
    readTime: "6 min read",
    date: "Oct 20, 2024",
    image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=1000&h=600&fit=crop",
  },
  {
    id: 12,
    title: "Static Site Generators: The Future of the Web?",
    excerpt: "Evaluating the benefits of static site generators for performance and scalability.",
    categories: ["Trends", "Static Sites", "Jamstack"],
    readTime: "9 min read",
    date: "Oct 15, 2024",
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1000&h=600&fit=crop",
  },
  {
    id: 13,
    title: "Animations in Web Development",
    excerpt: "Enhancing user engagement with smooth and meaningful animations.",
    categories: ["Design", "Animation", "Motion"],
    readTime: "7 min read",
    date: "Oct 10, 2024",
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1000&h=600&fit=crop",
  },
  {
    id: 14,
    title: "Demystifying API Architecture",
    excerpt: "A guide to understanding REST, GraphQL, and the future of API design.",
    categories: ["Development", "APIs", "Architecture"],
    readTime: "8 min read",
    date: "Oct 5, 2024",
    image: "https://images.unsplash.com/photo-1559028012-481c41f570e5?w=1000&h=600&fit=crop",
  },
  {
    id: 15,
    title: "Building a Design System",
    excerpt: "Streamlining your workflow with a consistent and reusable set of design patterns.",
    categories: ["Design", "Systems", "Best Practices"],
    readTime: "6 min read",
    date: "Oct 1, 2024",
    image: "https://images.unsplash.com/photo-1506765515384-028b60a970df?w=1000&h=600&fit=crop",
  },
  {
    id: 16,
    title: "Understanding Cloud Native Applications",
    excerpt: "Dive into the principles and tools for building scalable and robust cloud-native apps.",
    categories: ["Trends", "Cloud Native", "Containers"],
    readTime: "10 min read",
    date: "Sep 25, 2024",
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1000&h=600&fit=crop",
  },
];
const PAGE_SIZE = 9;

export { BLOG_POSTS, PAGE_SIZE };
